#:schema node_modules/wrangler/config-schema.json
name = "youtube-to-mp4-frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = "./dist"

[vars]
# Configure your backend API endpoint URL here
PUBLIC_API_URL = "/api"
# PUBLIC_TURNSTILE_SITE_KEY = ""
